# Generated by Django 5.1.1 on 2024-10-01 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tipo_de_solo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Canteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.espaco')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('necessidade_de_nutrientes', models.CharField(max_length=20)),
                ('ciclo_de_podagem', models.IntegerField()),
                ('ciclo_de_colheita', models.IntegerField()),
                ('canteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.canteiro')),
            ],
        ),
        migrations.CreateModel(
            name='InteracaoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacao', models.CharField(max_length=20)),
                ('tipo_de_interacao', models.CharField(max_length=20)),
                ('planta1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_como_planta1', to='plant.planta')),
                ('planta2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_como_planta2', to='plant.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Praga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_praga', models.CharField(max_length=30)),
                ('planta_afetada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pragas_afetam', to='plant.planta')),
                ('planta_afetada2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pragas_afetam2', to='plant.planta')),
                ('planta_repele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pragas_repelidas_por', to='plant.planta')),
                ('planta_repele2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pragas_repelidas_por2', to='plant.planta')),
            ],
        ),
    ]
