# Generated by Django 5.1.1 on 2024-10-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_remove_planta_canteiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='imagem',
            field=models.URLField(default=None, max_length=20),
        ),
    ]
