# Generated by Django 5.1.1 on 2024-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_planta_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteiro',
            name='quantMaxPlant',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='espaco',
            name='quantMaxCanteiro',
            field=models.IntegerField(default=5),
        ),
    ]
