# Generated by Django 5.1.1 on 2024-10-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_canteiro_quantmaxplant_espaco_quantmaxcanteiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='imagem',
            field=models.URLField(default=None),
        ),
        migrations.CreateModel(
            name='CanteiroPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('canteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.canteiro')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.planta')),
            ],
            options={
                'unique_together': {('canteiro', 'planta')},
            },
        ),
        migrations.AddField(
            model_name='canteiro',
            name='plantas',
            field=models.ManyToManyField(blank=True, through='plant.CanteiroPlanta', to='plant.planta'),
        ),
    ]
