# Generated by Django 5.1.1 on 2024-10-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_canteiro_quantmaxplant_espaco_quantmaxcanteiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteiro',
            name='plantas',
            field=models.ManyToManyField(related_name='canteiros', to='plant.planta'),
        ),
    ]
