# Generated by Django 5.1.1 on 2024-10-18 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
        ('plant', '0006_alter_planta_imagem_canteiroplanta_canteiro_plantas'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteiro',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
        migrations.AddField(
            model_name='espaco',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
        migrations.AddField(
            model_name='interacaoplanta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
        migrations.AddField(
            model_name='planta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
        migrations.AddField(
            model_name='praga',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
    ]
