# Generated by Django 5.1.1 on 2024-10-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_canteiro_plantas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteiro',
            name='plantas',
            field=models.ManyToManyField(blank=True, null=True, related_name='canteiros', to='plant.planta'),
        ),
    ]
