# Generated by Django 5.1.1 on 2024-10-18 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
        ('plant', '0007_canteiro_user_espaco_user_interacaoplanta_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteiro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
        migrations.AlterField(
            model_name='interacaoplanta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
        migrations.AlterField(
            model_name='praga',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
    ]
