# Generated by Django 5.1.1 on 2024-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_alter_canteiro_user_alter_espaco_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteiro',
            name='quantMaxPlant',
            field=models.IntegerField(),
        ),
    ]
