# Generated by Django 5.1.1 on 2024-11-20 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_planta_plantas_inimigas_alter_planta_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='plantas_inimigas',
        ),
        migrations.AddField(
            model_name='canteiroplanta',
            name='data_plantio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='planta',
            name='imagem',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='planta',
            name='necessidade_de_nutrientes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
