# Generated by Django 5.1.1 on 2024-11-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0012_planta_plantas_inimigas_alter_planta_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
